[2024-10-01T17:29:25.616+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T02:12:00+00:00 [queued]>
[2024-10-01T17:29:25.622+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T02:12:00+00:00 [queued]>
[2024-10-01T17:29:25.623+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-10-01T17:29:25.634+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_recommendation_system> on 2024-01-01 02:12:00+00:00
[2024-10-01T17:29:25.637+0000] {standard_task_runner.py:57} INFO - Started process 450 to run task
[2024-10-01T17:29:25.640+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'recommendation_dag', 'run_recommendation_system', 'scheduled__2024-01-01T02:12:00+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/recommendation_dag.py', '--cfg-path', '/tmp/tmpvvk14joi']
[2024-10-01T17:29:25.641+0000] {standard_task_runner.py:85} INFO - Job 169: Subtask run_recommendation_system
[2024-10-01T17:29:25.652+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-01T17:29:25.676+0000] {task_command.py:416} INFO - Running <TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T02:12:00+00:00 [running]> on host 67fc133b154a
[2024-10-01T17:29:25.723+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recommendation_dag' AIRFLOW_CTX_TASK_ID='run_recommendation_system' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T02:12:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T02:12:00+00:00'
[2024-10-01T17:29:25.729+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/recommendation_dag.py", line 17, in run_spark_job
    call(["spark-submit", "/sparkdata/recommendation.py"])
  File "/usr/local/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark-submit'
[2024-10-01T17:29:25.739+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=recommendation_dag, task_id=run_recommendation_system, execution_date=20240101T021200, start_date=20241001T172925, end_date=20241001T172925
[2024-10-01T17:29:25.753+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 169 for task run_recommendation_system ([Errno 13] Permission denied: 'spark-submit'; 450)
[2024-10-01T17:29:25.779+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-01T17:29:25.794+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T20:22:35.208+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T02:12:00+00:00 [queued]>
[2024-10-02T20:22:35.219+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T02:12:00+00:00 [queued]>
[2024-10-02T20:22:35.221+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-10-02T20:22:35.236+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_recommendation_system> on 2024-01-01 02:12:00+00:00
[2024-10-02T20:22:35.240+0000] {standard_task_runner.py:57} INFO - Started process 445 to run task
[2024-10-02T20:22:35.243+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'recommendation_dag', 'run_recommendation_system', 'scheduled__2024-01-01T02:12:00+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/recommendation_dag.py', '--cfg-path', '/tmp/tmpg4ixhjrq']
[2024-10-02T20:22:35.244+0000] {standard_task_runner.py:85} INFO - Job 132: Subtask run_recommendation_system
[2024-10-02T20:22:35.257+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-02T20:22:35.291+0000] {task_command.py:416} INFO - Running <TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T02:12:00+00:00 [running]> on host 2fa40570c946
[2024-10-02T20:22:35.368+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recommendation_dag' AIRFLOW_CTX_TASK_ID='run_recommendation_system' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T02:12:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T02:12:00+00:00'
[2024-10-02T20:22:35.377+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/recommendation_dag.py", line 17, in run_spark_job
    call(["spark-submit", "/sparkdata/recommendation.py"])
  File "/usr/local/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark-submit'
[2024-10-02T20:22:35.402+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=recommendation_dag, task_id=run_recommendation_system, execution_date=20240101T021200, start_date=20241002T202235, end_date=20241002T202235
[2024-10-02T20:22:35.414+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 132 for task run_recommendation_system ([Errno 13] Permission denied: 'spark-submit'; 445)
[2024-10-02T20:22:35.424+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-02T20:22:35.448+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
