[2024-10-01T19:52:09.426+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T04:12:00+00:00 [queued]>
[2024-10-01T19:52:09.441+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T04:12:00+00:00 [queued]>
[2024-10-01T19:52:09.442+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-10-01T19:52:09.455+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_recommendation_system> on 2024-01-01 04:12:00+00:00
[2024-10-01T19:52:09.461+0000] {standard_task_runner.py:57} INFO - Started process 158 to run task
[2024-10-01T19:52:09.489+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'recommendation_dag', 'run_recommendation_system', 'scheduled__2024-01-01T04:12:00+00:00', '--job-id', '312', '--raw', '--subdir', 'DAGS_FOLDER/recommendation_dag.py', '--cfg-path', '/tmp/tmpupq1n8rv']
[2024-10-01T19:52:09.497+0000] {standard_task_runner.py:85} INFO - Job 312: Subtask run_recommendation_system
[2024-10-01T19:52:09.540+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-01T19:52:09.652+0000] {task_command.py:416} INFO - Running <TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T04:12:00+00:00 [running]> on host 117b242ef823
[2024-10-01T19:52:09.804+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recommendation_dag' AIRFLOW_CTX_TASK_ID='run_recommendation_system' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T04:12:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T04:12:00+00:00'
[2024-10-01T19:52:09.823+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/recommendation_dag.py", line 17, in run_spark_job
    call(["spark-submit", "/sparkdata/recommendation.py"])
  File "/usr/local/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark-submit'
[2024-10-01T19:52:09.852+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=recommendation_dag, task_id=run_recommendation_system, execution_date=20240101T041200, start_date=20241001T195209, end_date=20241001T195209
[2024-10-01T19:52:09.889+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 312 for task run_recommendation_system ([Errno 13] Permission denied: 'spark-submit'; 158)
[2024-10-01T19:52:09.908+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-01T19:52:09.953+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T20:32:03.060+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T04:12:00+00:00 [queued]>
[2024-10-02T20:32:03.067+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T04:12:00+00:00 [queued]>
[2024-10-02T20:32:03.068+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-10-02T20:32:03.082+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_recommendation_system> on 2024-01-01 04:12:00+00:00
[2024-10-02T20:32:03.086+0000] {standard_task_runner.py:57} INFO - Started process 188 to run task
[2024-10-02T20:32:03.089+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'recommendation_dag', 'run_recommendation_system', 'scheduled__2024-01-01T04:12:00+00:00', '--job-id', '255', '--raw', '--subdir', 'DAGS_FOLDER/recommendation_dag.py', '--cfg-path', '/tmp/tmpykoxu43t']
[2024-10-02T20:32:03.090+0000] {standard_task_runner.py:85} INFO - Job 255: Subtask run_recommendation_system
[2024-10-02T20:32:03.101+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-02T20:32:03.161+0000] {task_command.py:416} INFO - Running <TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T04:12:00+00:00 [running]> on host d68b641ebafa
[2024-10-02T20:32:03.188+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-10-02T20:32:03.211+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recommendation_dag' AIRFLOW_CTX_TASK_ID='run_recommendation_system' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T04:12:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T04:12:00+00:00'
[2024-10-02T20:32:03.211+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/recommendation_dag.py", line 20, in run_spark_job
    job_id = execution_date.strftime('%Y-%m-%d_%H-%M-%S')
AttributeError: 'str' object has no attribute 'strftime'
[2024-10-02T20:32:03.217+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=recommendation_dag, task_id=run_recommendation_system, execution_date=20240101T041200, start_date=20241002T203203, end_date=20241002T203203
[2024-10-02T20:32:03.224+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 255 for task run_recommendation_system ('str' object has no attribute 'strftime'; 188)
[2024-10-02T20:32:03.230+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-02T20:32:03.244+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
