[2024-10-01T19:49:52.262+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T04:02:00+00:00 [queued]>
[2024-10-01T19:49:52.279+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T04:02:00+00:00 [queued]>
[2024-10-01T19:49:52.279+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-10-01T19:49:52.317+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_recommendation_system> on 2024-01-01 04:02:00+00:00
[2024-10-01T19:49:52.331+0000] {standard_task_runner.py:57} INFO - Started process 77 to run task
[2024-10-01T19:49:52.344+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'recommendation_dag', 'run_recommendation_system', 'scheduled__2024-01-01T04:02:00+00:00', '--job-id', '288', '--raw', '--subdir', 'DAGS_FOLDER/recommendation_dag.py', '--cfg-path', '/tmp/tmpve_rpfcv']
[2024-10-01T19:49:52.347+0000] {standard_task_runner.py:85} INFO - Job 288: Subtask run_recommendation_system
[2024-10-01T19:49:52.397+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-01T19:49:52.495+0000] {task_command.py:416} INFO - Running <TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T04:02:00+00:00 [running]> on host 117b242ef823
[2024-10-01T19:49:52.578+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recommendation_dag' AIRFLOW_CTX_TASK_ID='run_recommendation_system' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T04:02:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T04:02:00+00:00'
[2024-10-01T19:49:52.591+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/recommendation_dag.py", line 17, in run_spark_job
    call(["spark-submit", "/sparkdata/recommendation.py"])
  File "/usr/local/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark-submit'
[2024-10-01T19:49:52.609+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=recommendation_dag, task_id=run_recommendation_system, execution_date=20240101T040200, start_date=20241001T194952, end_date=20241001T194952
[2024-10-01T19:49:52.636+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 288 for task run_recommendation_system ([Errno 13] Permission denied: 'spark-submit'; 77)
[2024-10-01T19:49:52.655+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-01T19:49:52.674+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T20:32:01.676+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T04:02:00+00:00 [queued]>
[2024-10-02T20:32:01.683+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T04:02:00+00:00 [queued]>
[2024-10-02T20:32:01.685+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-10-02T20:32:01.696+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_recommendation_system> on 2024-01-01 04:02:00+00:00
[2024-10-02T20:32:01.700+0000] {standard_task_runner.py:57} INFO - Started process 173 to run task
[2024-10-02T20:32:01.702+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'recommendation_dag', 'run_recommendation_system', 'scheduled__2024-01-01T04:02:00+00:00', '--job-id', '254', '--raw', '--subdir', 'DAGS_FOLDER/recommendation_dag.py', '--cfg-path', '/tmp/tmpju4mbqzu']
[2024-10-02T20:32:01.704+0000] {standard_task_runner.py:85} INFO - Job 254: Subtask run_recommendation_system
[2024-10-02T20:32:01.713+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-02T20:32:01.740+0000] {task_command.py:416} INFO - Running <TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T04:02:00+00:00 [running]> on host d68b641ebafa
[2024-10-02T20:32:01.789+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recommendation_dag' AIRFLOW_CTX_TASK_ID='run_recommendation_system' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T04:02:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T04:02:00+00:00'
[2024-10-02T20:32:01.798+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/recommendation_dag.py", line 17, in run_spark_job
    # Define the function to run the Spark job
  File "/usr/local/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark-submit'
[2024-10-02T20:32:01.808+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=recommendation_dag, task_id=run_recommendation_system, execution_date=20240101T040200, start_date=20241002T203201, end_date=20241002T203201
[2024-10-02T20:32:01.815+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 254 for task run_recommendation_system ([Errno 13] Permission denied: 'spark-submit'; 173)
[2024-10-02T20:32:01.844+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-02T20:32:01.855+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
