[2024-10-01T19:49:52.255+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T04:06:00+00:00 [queued]>
[2024-10-01T19:49:52.282+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T04:06:00+00:00 [queued]>
[2024-10-01T19:49:52.285+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-10-01T19:49:52.320+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_recommendation_system> on 2024-01-01 04:06:00+00:00
[2024-10-01T19:49:52.324+0000] {standard_task_runner.py:57} INFO - Started process 75 to run task
[2024-10-01T19:49:52.339+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'recommendation_dag', 'run_recommendation_system', 'scheduled__2024-01-01T04:06:00+00:00', '--job-id', '285', '--raw', '--subdir', 'DAGS_FOLDER/recommendation_dag.py', '--cfg-path', '/tmp/tmp4p7k8a3l']
[2024-10-01T19:49:52.342+0000] {standard_task_runner.py:85} INFO - Job 285: Subtask run_recommendation_system
[2024-10-01T19:49:52.370+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-01T19:49:52.456+0000] {task_command.py:416} INFO - Running <TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T04:06:00+00:00 [running]> on host 117b242ef823
[2024-10-01T19:49:52.558+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recommendation_dag' AIRFLOW_CTX_TASK_ID='run_recommendation_system' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T04:06:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T04:06:00+00:00'
[2024-10-01T19:49:52.570+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/recommendation_dag.py", line 17, in run_spark_job
    call(["spark-submit", "/sparkdata/recommendation.py"])
  File "/usr/local/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark-submit'
[2024-10-01T19:49:52.600+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=recommendation_dag, task_id=run_recommendation_system, execution_date=20240101T040600, start_date=20241001T194952, end_date=20241001T194952
[2024-10-01T19:49:52.626+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 285 for task run_recommendation_system ([Errno 13] Permission denied: 'spark-submit'; 75)
[2024-10-01T19:49:52.655+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-01T19:49:52.680+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T20:32:03.058+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T04:06:00+00:00 [queued]>
[2024-10-02T20:32:03.064+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T04:06:00+00:00 [queued]>
[2024-10-02T20:32:03.065+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-10-02T20:32:03.081+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_recommendation_system> on 2024-01-01 04:06:00+00:00
[2024-10-02T20:32:03.085+0000] {standard_task_runner.py:57} INFO - Started process 187 to run task
[2024-10-02T20:32:03.087+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'recommendation_dag', 'run_recommendation_system', 'scheduled__2024-01-01T04:06:00+00:00', '--job-id', '256', '--raw', '--subdir', 'DAGS_FOLDER/recommendation_dag.py', '--cfg-path', '/tmp/tmpftfqte22']
[2024-10-02T20:32:03.089+0000] {standard_task_runner.py:85} INFO - Job 256: Subtask run_recommendation_system
[2024-10-02T20:32:03.097+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-02T20:32:03.152+0000] {task_command.py:416} INFO - Running <TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T04:06:00+00:00 [running]> on host d68b641ebafa
[2024-10-02T20:32:03.180+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-10-02T20:32:03.203+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recommendation_dag' AIRFLOW_CTX_TASK_ID='run_recommendation_system' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T04:06:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T04:06:00+00:00'
[2024-10-02T20:32:03.204+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/recommendation_dag.py", line 20, in run_spark_job
    job_id = execution_date.strftime('%Y-%m-%d_%H-%M-%S')
AttributeError: 'str' object has no attribute 'strftime'
[2024-10-02T20:32:03.212+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=recommendation_dag, task_id=run_recommendation_system, execution_date=20240101T040600, start_date=20241002T203203, end_date=20241002T203203
[2024-10-02T20:32:03.219+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 256 for task run_recommendation_system ('str' object has no attribute 'strftime'; 187)
[2024-10-02T20:32:03.228+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-02T20:32:03.242+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
