[2024-10-01T17:25:20.928+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T01:28:00+00:00 [queued]>
[2024-10-01T17:25:20.933+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T01:28:00+00:00 [queued]>
[2024-10-01T17:25:20.933+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-10-01T17:25:20.968+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_recommendation_system> on 2024-01-01 01:28:00+00:00
[2024-10-01T17:25:20.970+0000] {standard_task_runner.py:57} INFO - Started process 288 to run task
[2024-10-01T17:25:20.972+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'recommendation_dag', 'run_recommendation_system', 'scheduled__2024-01-01T01:28:00+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/recommendation_dag.py', '--cfg-path', '/tmp/tmp0kjskz3u']
[2024-10-01T17:25:20.973+0000] {standard_task_runner.py:85} INFO - Job 115: Subtask run_recommendation_system
[2024-10-01T17:25:20.981+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-01T17:25:21.004+0000] {task_command.py:416} INFO - Running <TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T01:28:00+00:00 [running]> on host 67fc133b154a
[2024-10-01T17:25:21.053+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recommendation_dag' AIRFLOW_CTX_TASK_ID='run_recommendation_system' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T01:28:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T01:28:00+00:00'
[2024-10-01T17:25:21.058+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/recommendation_dag.py", line 17, in run_spark_job
    call(["spark-submit", "/sparkdata/recommendation.py"])
  File "/usr/local/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark-submit'
[2024-10-01T17:25:21.069+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=recommendation_dag, task_id=run_recommendation_system, execution_date=20240101T012800, start_date=20241001T172520, end_date=20241001T172521
[2024-10-01T17:25:21.079+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 115 for task run_recommendation_system ([Errno 13] Permission denied: 'spark-submit'; 288)
[2024-10-01T17:25:21.109+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-01T17:25:21.122+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T20:18:27.172+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T01:28:00+00:00 [queued]>
[2024-10-02T20:18:27.179+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T01:28:00+00:00 [queued]>
[2024-10-02T20:18:27.179+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-10-02T20:18:27.186+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_recommendation_system> on 2024-01-01 01:28:00+00:00
[2024-10-02T20:18:27.189+0000] {standard_task_runner.py:57} INFO - Started process 283 to run task
[2024-10-02T20:18:27.192+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'recommendation_dag', 'run_recommendation_system', 'scheduled__2024-01-01T01:28:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/recommendation_dag.py', '--cfg-path', '/tmp/tmp4hhho69c']
[2024-10-02T20:18:27.193+0000] {standard_task_runner.py:85} INFO - Job 78: Subtask run_recommendation_system
[2024-10-02T20:18:27.201+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-02T20:18:27.232+0000] {task_command.py:416} INFO - Running <TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T01:28:00+00:00 [running]> on host 2fa40570c946
[2024-10-02T20:18:27.283+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recommendation_dag' AIRFLOW_CTX_TASK_ID='run_recommendation_system' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T01:28:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T01:28:00+00:00'
[2024-10-02T20:18:27.295+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/recommendation_dag.py", line 17, in run_spark_job
    call(["spark-submit", "/sparkdata/recommendation.py"])
  File "/usr/local/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark-submit'
[2024-10-02T20:18:27.310+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=recommendation_dag, task_id=run_recommendation_system, execution_date=20240101T012800, start_date=20241002T201827, end_date=20241002T201827
[2024-10-02T20:18:27.325+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 78 for task run_recommendation_system ([Errno 13] Permission denied: 'spark-submit'; 283)
[2024-10-02T20:18:27.330+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-02T20:18:27.347+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
