[2024-10-01T22:42:49.910+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T06:04:00+00:00 [queued]>
[2024-10-01T22:42:49.921+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T06:04:00+00:00 [queued]>
[2024-10-01T22:42:49.924+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-10-01T22:42:49.938+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_recommendation_system> on 2024-01-01 06:04:00+00:00
[2024-10-01T22:42:49.941+0000] {standard_task_runner.py:57} INFO - Started process 118 to run task
[2024-10-01T22:42:49.944+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'recommendation_dag', 'run_recommendation_system', 'scheduled__2024-01-01T06:04:00+00:00', '--job-id', '433', '--raw', '--subdir', 'DAGS_FOLDER/recommendation_dag.py', '--cfg-path', '/tmp/tmpiz6p3gho']
[2024-10-01T22:42:49.945+0000] {standard_task_runner.py:85} INFO - Job 433: Subtask run_recommendation_system
[2024-10-01T22:42:49.965+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-01T22:42:50.005+0000] {task_command.py:416} INFO - Running <TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T06:04:00+00:00 [running]> on host c1d510772263
[2024-10-01T22:42:50.055+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recommendation_dag' AIRFLOW_CTX_TASK_ID='run_recommendation_system' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T06:04:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T06:04:00+00:00'
[2024-10-01T22:42:50.062+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/recommendation_dag.py", line 17, in run_spark_job
    call(["spark-submit", "/sparkdata/recommendation.py"])
  File "/usr/local/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark-submit'
[2024-10-01T22:42:50.071+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=recommendation_dag, task_id=run_recommendation_system, execution_date=20240101T060400, start_date=20241001T224249, end_date=20241001T224250
[2024-10-01T22:42:50.078+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 433 for task run_recommendation_system ([Errno 13] Permission denied: 'spark-submit'; 118)
[2024-10-01T22:42:50.085+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-01T22:42:50.125+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-01T22:44:30.757+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T06:04:00+00:00 [queued]>
[2024-10-01T22:44:30.762+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T06:04:00+00:00 [queued]>
[2024-10-01T22:44:30.763+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-10-01T22:44:30.769+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_recommendation_system> on 2024-01-01 06:04:00+00:00
[2024-10-01T22:44:30.772+0000] {standard_task_runner.py:57} INFO - Started process 160 to run task
[2024-10-01T22:44:30.774+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'recommendation_dag', 'run_recommendation_system', 'scheduled__2024-01-01T06:04:00+00:00', '--job-id', '447', '--raw', '--subdir', 'DAGS_FOLDER/recommendation_dag.py', '--cfg-path', '/tmp/tmp8rdmtvfi']
[2024-10-01T22:44:30.775+0000] {standard_task_runner.py:85} INFO - Job 447: Subtask run_recommendation_system
[2024-10-01T22:44:30.782+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-01T22:44:30.808+0000] {task_command.py:416} INFO - Running <TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T06:04:00+00:00 [running]> on host c1d510772263
[2024-10-01T22:44:30.854+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recommendation_dag' AIRFLOW_CTX_TASK_ID='run_recommendation_system' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T06:04:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T06:04:00+00:00'
[2024-10-01T22:44:30.860+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/recommendation_dag.py", line 17, in run_spark_job
    call(["spark-submit", "/sparkdata/recommendation.py"])
  File "/usr/local/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark-submit'
[2024-10-01T22:44:30.872+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=recommendation_dag, task_id=run_recommendation_system, execution_date=20240101T060400, start_date=20241001T224430, end_date=20241001T224430
[2024-10-01T22:44:30.880+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 447 for task run_recommendation_system ([Errno 13] Permission denied: 'spark-submit'; 160)
[2024-10-01T22:44:30.913+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-01T22:44:30.927+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
