[2024-10-01T17:27:22.838+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T01:38:00+00:00 [queued]>
[2024-10-01T17:27:22.847+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T01:38:00+00:00 [queued]>
[2024-10-01T17:27:22.847+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-10-01T17:27:22.856+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_recommendation_system> on 2024-01-01 01:38:00+00:00
[2024-10-01T17:27:22.860+0000] {standard_task_runner.py:57} INFO - Started process 351 to run task
[2024-10-01T17:27:22.862+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'recommendation_dag', 'run_recommendation_system', 'scheduled__2024-01-01T01:38:00+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/recommendation_dag.py', '--cfg-path', '/tmp/tmpbt1w1kew']
[2024-10-01T17:27:22.863+0000] {standard_task_runner.py:85} INFO - Job 136: Subtask run_recommendation_system
[2024-10-01T17:27:22.871+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-01T17:27:22.900+0000] {task_command.py:416} INFO - Running <TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T01:38:00+00:00 [running]> on host 67fc133b154a
[2024-10-01T17:27:22.951+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recommendation_dag' AIRFLOW_CTX_TASK_ID='run_recommendation_system' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T01:38:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T01:38:00+00:00'
[2024-10-01T17:27:22.958+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/recommendation_dag.py", line 17, in run_spark_job
    call(["spark-submit", "/sparkdata/recommendation.py"])
  File "/usr/local/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark-submit'
[2024-10-01T17:27:22.968+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=recommendation_dag, task_id=run_recommendation_system, execution_date=20240101T013800, start_date=20241001T172722, end_date=20241001T172722
[2024-10-01T17:27:22.979+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 136 for task run_recommendation_system ([Errno 13] Permission denied: 'spark-submit'; 351)
[2024-10-01T17:27:23.001+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-01T17:27:23.038+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T20:20:30.214+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T01:38:00+00:00 [queued]>
[2024-10-02T20:20:30.224+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T01:38:00+00:00 [queued]>
[2024-10-02T20:20:30.225+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-10-02T20:20:30.235+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_recommendation_system> on 2024-01-01 01:38:00+00:00
[2024-10-02T20:20:30.240+0000] {standard_task_runner.py:57} INFO - Started process 344 to run task
[2024-10-02T20:20:30.243+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'recommendation_dag', 'run_recommendation_system', 'scheduled__2024-01-01T01:38:00+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/recommendation_dag.py', '--cfg-path', '/tmp/tmp4hwag0ws']
[2024-10-02T20:20:30.243+0000] {standard_task_runner.py:85} INFO - Job 99: Subtask run_recommendation_system
[2024-10-02T20:20:30.253+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-02T20:20:30.284+0000] {task_command.py:416} INFO - Running <TaskInstance: recommendation_dag.run_recommendation_system scheduled__2024-01-01T01:38:00+00:00 [running]> on host 2fa40570c946
[2024-10-02T20:20:30.344+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recommendation_dag' AIRFLOW_CTX_TASK_ID='run_recommendation_system' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T01:38:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T01:38:00+00:00'
[2024-10-02T20:20:30.353+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/recommendation_dag.py", line 17, in run_spark_job
    call(["spark-submit", "/sparkdata/recommendation.py"])
  File "/usr/local/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark-submit'
[2024-10-02T20:20:30.367+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=recommendation_dag, task_id=run_recommendation_system, execution_date=20240101T013800, start_date=20241002T202030, end_date=20241002T202030
[2024-10-02T20:20:30.377+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 99 for task run_recommendation_system ([Errno 13] Permission denied: 'spark-submit'; 344)
[2024-10-02T20:20:30.426+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-02T20:20:30.445+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
